#!/bin/bash

RED='\E[1;31m'
RED_W='\E[41;37m'
END='\E[0m'
remote="" && path=""
this_name=`basename $0`

curr_date(){
        curr_date=`date +[%Y-%m-%d"_"%H:%M:%S]`
        echo -e "`red $(date +[%Y-%m-%d_%H:%M:%S])`"
}
red(){
        echo -e "${RED}${1}${END}"
}
mount(){
	fusermount -qzu "${path}" > /dev/null 2>&1
	rclone mount "${remote}": "${path}" --transfers 10  --buffer-size 1G --vfs-read-chunk-size 256M --vfs-read-chunk-size-limit 2G  --allow-non-empty --allow-other --dir-cache-time 12h --umask 000 >/dev/null 2>&1 & 
	sleep 3s
    	ps -ef | grep -v grep | grep -q "${remote}"
	if [ "$?" -eq "0" ];then
		echo -e "已将 `red ${remote}` 挂载到 `red ${path}`."
	else
		echo -e "`red 挂载失败。请联系脚本作者排查原因！`"
		exit 1
	fi
}
11plus_start(){
	echo -e "`red 正在为您创建挂载服务,请稍等...`"
	echo
	if [[ ! -d ${path} ]];then
            echo
            echo -e "`curr_date`  ${RED}${path}${END} 不存在，正在创建..."
            mkdir -p ${path}
            sleep 1s
            echo
            echo -e "`curr_date` 创建完成！"
	    echo
    	fi
	mount
	echo
	exit 0
}

11plus_stop(){
	echo
    	df -h | grep -q "${remote}:"
    	if [ $? -eq 0 ];then
        	echo -e "`red 正在停用${remote}挂载,请稍等...`"
        	echo
        	fusermount -qzu "${path}" > /dev/null 2>&1
        	sleep 3s
        	echo -e "`red 停用${this_name}成功！`"
		echo
        	exit 0
    	else
        	echo -e "`red ${remote}` 未挂载，勿需停用服务。"
        	echo
        	exit 1
    	fi
}

11plus_restart(){
	echo -e "`red 正在重新挂载,请稍等...`"
	echo
	mount
}
11plus_status(){
	df -h | grep -q "${remote}:"
    	if [ $? -eq 0 ];then
		echo -e "`red ${remote}` 挂载状态: `red 正常`"
		echo -e "挂载服务地址: `red /usr/bin/${this_name}`\n挂载路径: `red ${path}`\n您可以直接使用${this_name} `red 'start|stop|restart|status'` 来管理服务."
	else
		echo -e "`red ${this_name}` 挂载状态 `red 异常`"
		
	fi
	
}


case $1 in
	start | stop | restart | status)
		11plus_$1;;
	*)
		echo
		echo "输入错误，脚本只支持 `red 'start|stop|restart|status'`.请从新运行脚本."
		echo
		exit 1
esac
